### ISSUE TITLE
workspace or data source is read only

### ISSUE THREAD

**Issue by iTravelingLight** [Esri/arcobjects-sdk-community-samples#2]
Hi，i hava a problem about this project “arcobjects-sdk-community-samples/Net/Server/ServerEditFeaturesRESTSOE/”.

  // store feature in feature class
  feature.Store();

This codes prompts "workspace or data source is read only".
My ArcGIS Server Version is 10.3. 
Can you give me a favor?
Tks.

**Comment by arcgisprosdk** [comment]
Sorry about the late reply.  Server sample questions are best answered on GeoNet in the [Server Object Extensions & Server Object Interceptors Group](https://geonet.esri.com/groups/server-object-extensions-server-object-interceptors)
