### ISSUE TITLE
NetSimpleRESTSOEWithProperties.html mssing in SimpleRESTSOEWithProperties sample

### ISSUE THREAD

**Issue by esride-ral** [Esri/arcobjects-sdk-community-samples#3]
The file Config.js is referencing a file called NetSimpleRESTSOEWithProperties.html. According to the "csproj" this html file should be located in a folder called "templates". But there is no such folder.

**Comment by Wolf-K** [comment]
You can find the missing file here:
[https://github.com/Esri/arcobjects-sdk-community-samples/tree/master/Net/Server/ServerSimpleRESTSOEWithProperties/CSharp/SimpleRESTSOEWithProperties/Resources/NetRESTSOEProperties/NetSimpleRESTSOEWithProperties/templates](https://github.com/Esri/arcobjects-sdk-community-samples/tree/master/Net/Server/ServerSimpleRESTSOEWithProperties/CSharp/SimpleRESTSOEWithProperties/Resources/NetRESTSOEProperties/NetSimpleRESTSOEWithProperties/templates)
